### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by InzeNL** [DavidBergevoet/Setup-Reservation#30]
We should define standards and enforce them using Github actions. There is pylint that can help with this. Editorconfig also comes to mind, though there doesn't seem to be an amazing way to enforce this one.

**Comment by DavidBergevoet** [comment]
You can use [autopep8](https://pypi.org/project/autopep8/) to beautify python code to the pep8 standard.
You can also use this in a github action to check if all the code is conform pep8 and otherwise fail the action.
Add a section in the README.md with a tutorial on how to format the code with autopep8

**Comment by InzeNL** [comment]
https://pypi.org/project/autoflake/

Is this something to use?

**Comment by InzeNL** [comment]
https://github.com/m-burst/flake8-pytest-style
